### PR TITLE
Add tfoot support

### PR DESCRIPTION
**Pull request by samtsai**
For my project I needed a meaningful way to represent totals for columns. I like how simple your components are so I tried to maintain that approach.

There are no external API changes, just a few new flags internally. Therefore, I opted to not require the implementers to have to add a new field, but rather with their existing `data` array, they need to append an `isFooterRow` flag to their data. You can see it in the demo and readme.

### CODE REVIEW

**Comment by samtsai** [comment]
@freekmurze @sebastiandedeyne what do you guys think of this idea, I'm open to different implementations. There are caveats like it's a little strange to use an existing column field but use a generic term like "Total" just to give a proper label to the footer rows (potentially have footer columns in the future?).

**Comment by freekmurze** [comment]
I'm going to pass on this one. We don't need this feature ourselves and I'd like to keep the package very simple.

Of course you're welcome to fork our code and modify it in any way you want.

**Comment by samtsai** [comment]
@freekmurze thanks for the response. Curious, do any projects show a summary row? If so, is that just a completely separate section from the table?

**Comment by freekmurze** [comment]
I don't think we show a summary row in any recent project 😄

**Comment by samtsai** [comment]
@freekmurze how would you feel about allowing a named slot for `tfoot`. I would really like to use the project as is and not a fork, and looking to avoid a hack that appends a `tfoot` section after the component is mounted.

```
                <tbody>
                <table-row
                    v-for="row in displayedRows"
                    :key="row.vueTableComponentInternalRowId"
                    :row="row"
                    :columns="columns"
                ></table-row>
                </tbody>
                <tfoot>
                    <slot name="footer">Footer</slot>
                </tfoot>
```

Could either render an empty `<tfoot>` for most users (including yourselves) or not even include the wrapping markup and leave just the `slot name="footer"` to be filled out by the user.

**Pull request closed without merging**
