### PR TITLE
#3 added an additional prop styles

### PR DESCRIPTION
**Pull request by amitavroy**
#3 added an additional prop styles so that user can add custom classes to the table and use it with frameworks like Bootstrap which requires table class for the styling.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for this.

Wouldn't it be better if that prop was named `class` instead of `styles`?
Could you also add a test to prove that this works?

**Comment by amitavroy** [comment]
I can rename the prop no problem.

But, I am really sorry but I have no knowledge of writing test in
JavaScript.

Just started to get my hands on phpunit.

Does that mean pull request doesn't qualify?

**Comment by freekmurze** [comment]
Nah, I'll write a little test for it myself, no problem.

Getting started with Vue tests can, like tests in PHP, be a bit overwhelming. Here were [my experiences learning it](https://murze.be/2017/05/testing-vue-component-part-1-getting-started/).

**Comment by amitavroy** [comment]
Sure, thanks for the link. A **promise**, I will pick up tests for Vue soon 👍

**Comment by freekmurze** [comment]
@sebastiandedeyne can we make it work with `class` somehow?

**Comment by mikemand** [comment]
I thought I read somewhere that you can apply classes to the component (e.x. `<table-component class="table table-hover">`) and they will be passed through and merged with the component's rendered HTML?

**Comment by sebastiandedeyne** [comment]
@mikemand True, but that only applies to the top level component. As a package user, you wouldn't be able to style the table or the header or the search field for example.

Why not pass an object of classes for the various elements?

```
<table :classes="{ row: '...', 'input': '...' }">
```

**Comment by amitavroy** [comment]
@sebastiandedeyne do let me know if there is a way that we can use class as a prop and send it to the component.

It was not possible and hence the prop is still using styles as the keyword. Let me know.

**Comment by freekmurze** [comment]
Hi, we are going to implement this differently. Thanks for your efforts though.

**Comment by amitavroy** [comment]
Ok, let me know how you are going to do it.

**Comment by freekmurze** [comment]
Our solution has been merged in.

**Pull request closed without merging**
