### PR TITLE
Set Table Head Class

### PR DESCRIPTION
**Pull request by faustbrian**
Solves https://github.com/spatie/vue-table-component/issues/60

### CODE REVIEW

**Comment by willemvb** [comment]
Thanks, that was fast!
Can you bring the `README.md` up to date as well?

**Comment by faustbrian** [comment]
Done

**Comment by willemvb** [comment]
Ah, one more thing: `settings.js` should be updated as well.

**Comment by faustbrian** [comment]
Done

**Comment by freekmurze** [comment]
Thanks! 👍

**Comment by freekmurze** [comment]
Changes have been published as version 1.5.0.

**Pull request merged**
