### PR TITLE
make getSortableValue() more robust and better able to handle dates

### PR DESCRIPTION
**Pull request by pieterjandesmedt**

### CODE REVIEW

**Comment by pieterjandesmedt** [comment]
This also closes #77.

**Comment by Lloople** [comment]
Hi @pieterjandesmedt I would like yo contribute to your PR by adding tests

**Comment by pieterjandesmedt** [comment]
Thanks, be my guest!

**Comment by Lloople** [comment]
I think you should allow me to clone your PR and push commit to it. I found this link, hope it may help https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by pieterjandesmedt** [comment]
The 'Allow edits from maintainers' is checked...

**Comment by Lloople** [comment]
@pieterjandesmedt I was able to clone your fork and checkout your branch but I couldn't make a push 😅 @freekmurze can you help us to accomplish this please? It's my first time pushing to another person's PR

**Comment by sebastiandedeyne** [comment]
Hi! Thanks for this PR. The current version of the table-component became too hard to maintain for us, and we've got dozens of feature requests that we can't cater too. 

We're not going to do any more 1.X releases, unless it's a critical bugfix. We'll do our best to add this feature in the next major version of the package.

**Pull request closed without merging**
